# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [2]:
!pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.4-cp39-cp39-macosx_11_0_arm64.whl.metadata (9.2 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in /Users/gnancy/.pyenv/versions/3.9.2/lib/python3.9/site-packages (from statsmodels) (2.0.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /Users/gnancy/.pyenv/versions/3.9.2/lib/python3.9/site-packages (from statsmodels) (1.13.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /Users/gnancy/.pyenv/versions/3.9.2/lib/python3.9/site-packages (from statsmodels) (2.2.3)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: packaging>=21.3 in /Users/gnancy/.pyenv/versions/3.9.2/lib/python3.9/site-packages (from statsmodels) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/gnancy/.pyenv/versions/3.9.2/lib/python3.9/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/gnancy/.pyenv/versions/3.9.2/lib/python3.9/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/gnancy/.pyenv/versions/3.9.2/lib/python3.9/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.1)
Requirement already satisfied: six>=1.5 in /Users/gnancy/.pyenv/versions/3.9.2/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Downloading statsmodels-0.14.4-cp39-cp39-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 12.5 MB/s eta 0:00:00a 0:00:01
Downloading patsy-1.0.1-py2.py3-none-any.whl (232 kB)
Installing collected packages: patsy, statsmodels
Successfully installed patsy-1.0.1 statsmodels-0.14.4

In [48]:
# import numpy and pandas
import pandas as pd
import numpy as np
from scipy.stats import trim_mean, mode, skew, gaussian_kde, pearsonr, spearmanr, beta, norm
from statsmodels.stats.weightstats import ztest as ztest

from scipy.stats import ttest_ind, norm, t
from scipy.stats import f_oneway
from scipy.stats import sem

import scipy.stats as st

# Challenge 1 - Exploring the Data

In this challenge, we will examine all salaries of employees of the City of Chicago. We will start by loading the dataset and examining its contents

In [4]:
# Run this code:
salaries = pd.read_csv('../data/Current_Employee_Names__Salaries__and_Position_Titles.csv')

Examine the `salaries` dataset using the `head` function below.

In [21]:
# Your code here
print(salaries.shape)
salaries.sample(20)

(33183, 8)

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
32451,"WOJTECKI, KENNETH S",BATTALION CHIEF - EMT,FIRE,F,Salary,NaN,149502.0,NaN
23121,"PETTIS, ERICA L",ADMINISTRATIVE ASST II,FAMILY & SUPPORT,F,Salary,NaN,70092.0,NaN
27060,"SHAW, BRYAN R",FOREMAN OF CEMENT FINISHERS,TRANSPORTN,F,Hourly,40.0,NaN,46.25
30407,"VANCE, DORIAN D",FIREFIGHTER-EMT (RECRUIT),FIRE,F,Salary,NaN,68616.0,NaN
11840,"HARDING, TAMARA L",SUPVSR OF PERSONNEL SERVICES,BUSINESS AFFAIRS,F,Salary,NaN,89076.0,NaN
3925,"CAMPBELL, SHAKEETTA M",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,NaN,19.86
26239,"SANCHEZ, DEANNA M",EQUIPMENT DISPATCHER,STREETS & SAN,F,Hourly,40.0,NaN,36.22
32735,"YANG, LUYANG",CIVIL ENGINEER V,TRANSPORTN,F,Salary,NaN,120312.0,NaN
16887,"LINDQUIST, MARK P",FIREFIGHTER/PARAMEDIC,FIRE,F,Salary,NaN,94476.0,NaN
28156,"SPENCE, CHARLES",CHIEF PROGRAMMER/ANALYST EXCLUDED,FINANCE,F,Salary,NaN,112296.0,NaN
4758,"CHEEK BUTLER, GERRIN",MGR OF FOOD PROTECTION SERVICES,HEALTH,F,Salary,NaN,97692.0,NaN
8830,"FIGUEROA MITCHE, TINA M",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,103932.0,NaN
4320,"CARTER, SHYKELA S",INVESTIGATOR-COPA,COPA,F,Salary,NaN,101592.0,NaN
27196,"SHIELDS, BRENDAN J",POLICE OFFICER,POLICE,F,Salary,NaN,87006.0,NaN
14152,"JOHNSON, ANTHONY",MACHINIST (AUTOMOTIVE),GENERAL SERVICES,F,Hourly,40.0,NaN,46.35
18406,"MATIAS, ADRIANA S",PARALEGAL II,LAW,F,Salary,NaN,70092.0,NaN
7923,"DWYER, ANNE M",POLICE OFFICER,POLICE,F,Salary,NaN,90024.0,NaN
19238,"MEDICI, DANIEL S",POLICE OFFICER,POLICE,F,Salary,NaN,87006.0,NaN
17583,"MACKOWIAK, DANIEL",ELECTRICAL MECHANIC (AUTOMOTIVE),GENERAL SERVICES,F,Hourly,40.0,NaN,46.10
7646,"DOYLE, MATTHEW P",ARCHITECTURAL IRON WORKER,TRANSPORTN,F,Hourly,40.0,NaN,45.75

# Challenge 2
This is a placeholder to make the AI corrector be able to find the correct exercise for feedback

# Challenge 3 - Constructing Confidence Intervals

We will test whether the hourly wage of all hourly workers is significantly different from $30/hr.

In the cell below, we will construct a 95% confidence interval for the mean hourly wage of all hourly workers. Is $30/hr within that interval?

The confidence interval is computed in SciPy using the `t.interval` function. You can read more about this function [here](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.t.html).

To compute the confidence interval of the hourly wage, use the 0.95 for the confidence level, number of rows - 1 for degrees of freedom, the mean of the sample for the location parameter and the standard error for the scale. The standard error can be computed using [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) function in SciPy.

In [20]:
# Your code here
print('true mean: ',salaries['Hourly Rate'].mean(),'true sigma: ',salaries['Hourly Rate'].std(ddof=0))

def sigma(obs):
    num = np.sum((np.mean(obs)-obs)**2)
    den = len(obs)
    print(den)
    sigma_biased = np.sqrt(num/den)
    sigma_unbiased = np.sqrt(num/(den-1))
    return sigma_biased, sigma_unbiased

print(' sigma biased and unbiased: ', sigma(salaries['Hourly Rate']))

true mean:  32.78855771628023 true sigma:  12.111817701093825
33183
 sigma biased and unbiased:  (np.float64(5.955151723754995), np.float64(5.95524145775019))

In [25]:
# 95.5% confidence needs: Mean, number of observation, std of original
salaries_hourly_notna = salaries[salaries['Hourly Rate'].notna()]

print('true mean: ',salaries_hourly_notna['Hourly Rate'].mean(),'true sigma: ',salaries_hourly_notna['Hourly Rate'].std(ddof=0))
print(' sigma biased and unbiased: ', sigma(salaries_hourly_notna['Hourly Rate']))

true mean:  32.78855771628024 true sigma:  12.111817701093825
8022
 sigma biased and unbiased:  (np.float64(12.111817701093825), np.float64(12.112572684276799))

### Confidence Interval

In [54]:
salaries_hr_sample = salaries_hourly_notna.sample(1000)
salaries_hr_sample_mean = salaries_hr_sample['Hourly Rate'].mean()
salaries_hr_sample_std = salaries_hr_sample['Hourly Rate'].std()
salaries_df = len(salaries_hr_sample['Hourly Rate']) # degress of freedom

# Confidence interval with z-score
confidence_interval = 0.95
z = norm.ppf(confidence_interval) # 0.95 is confidence interval
t = st.t.ppf(1-((1-confidence_interval)/2), salaries_df-1)

print('salaries_hr_sample_mean x:', salaries_hr_sample_mean, '\n salaries_hr_sample_std s:', salaries_hr_sample_std, '\n degrees of freedom df:',salaries_df)

# Calculate 95% confidence interval
error_margin = 2*(salaries_hr_sample_std/np.sqrt(salaries_df))
z_error_margin = z*(salaries_hr_sample_std/np.sqrt(salaries_df))
t_error_margin = t*(salaries_hr_sample_std/np.sqrt(salaries_df))


print('\n 95% Confidence interval is :', salaries_hr_sample_mean-error_margin, "-", salaries_hr_sample_mean+error_margin)

# Using z-score python function 
print('\n 95% Confidence interval with z stats function is :', norm.interval(confidence_interval, loc=salaries_hr_sample_mean, scale=salaries_hr_sample_std/np.sqrt(salaries_df)))

print(f'95% Confidence interval(z-score:{z}) is :', salaries_hr_sample_mean-z_error_margin, "-", salaries_hr_sample_mean+z_error_margin)

# Using t-score python function 
print('\n95% Confidence interval with t stats function is :', st.t.interval(confidence_interval,salaries_df-1, loc=salaries_hr_sample_mean, scale=salaries_hr_sample_std/np.sqrt(salaries_df)))
print(f'95% Confidence interval(t-score:{t}) is :', salaries_hr_sample_mean-t_error_margin, "-", salaries_hr_sample_mean+t_error_margin)

salaries_hr_sample_mean x: 33.554190000000006
 salaries_hr_sample_std s: 11.988318277348956
 degrees of freedom df: 1000

 95% Confidence interval is : 32.79598217857103 - 34.31239782142898

 95% Confidence interval with z stats function is : (np.float64(32.81115998860132), np.float64(34.29722001139869))
95% Confidence interval(z-score:1.644853626951472) is : 32.93061955746979 - 34.17776044253022

95% Confidence interval with t stats function is : (np.float64(32.81025867792713), np.float64(34.29812132207288))
95% Confidence interval(t-score:1.9623414611334487) is : 32.81025867792713 - 34.29812132207288

### Computing number of samples needed

Confidence interval = [μ - t * s / √n , μ + t * s / √n]

W =   (μ + t * s / √n) - (μ - t * s / √n) = 2 * t * s / √n


Objective: n=?

W = 2 * t * s / √n         ⇔

√n * W = 2 * t * s         ⇔

√n = 2 * t * s / W         ⇔

n = (2 * t * s / W)2

In [53]:
def find_n(t,s,W):
    return (2*t*s/W)**2

def find_t(conf, n):
    return st.t.ppf(1-((1-conf)/2), n-1)

# Confidence interval with z-score
confidence_interval = 0.95
t0 = norm.ppf(1-(1-confidence_interval)/2)
s = salaries_hr_sample['Hourly Rate'].std()
W = 5

n_tmp = find_n(t0,s,W)
t1 = find_t(confidence_interval, n_tmp)
n1_tmp = find_n(t1,s,W)
t2 = find_t(confidence_interval, n1_tmp)
n2_tmp = find_n(t2,s,W)

print(f'beginning values - t0:{t0}, std:{s}, error_margin:{W}')
print(f' test - n0:{n_tmp},n1:{n1_tmp},n1:{n2_tmp} ')

beginning values - t0:1.959963984540054, std:12.784435287339118, error_margin:5
 test - n0:100.4567822440324,n1:102.9466084995244,n1:102.88471866139952

This is fine if we have thousands of worker data. But what if we have only 100 workers data?

Sample 100 workers and re-construct the 95% confidence interval. Is the interval wider of narrower? And why?
Do you still encapsulate the $30/hr mark in this case?

In [55]:
# Your code here

# Answwer: No, 95% confidence says average values are not in $30/hr and it is greater

salaries_hr_sample = salaries_hourly_notna.sample(100)
salaries_hr_sample_mean = salaries_hr_sample['Hourly Rate'].mean()
salaries_hr_sample_std = salaries_hr_sample['Hourly Rate'].std()
salaries_df = len(salaries_hr_sample['Hourly Rate']) # degress of freedom

# Confidence interval with z-score
confidence_interval = 0.95
z = norm.ppf(confidence_interval) # 0.95 is confidence interval
t = st.t.ppf(1-((1-confidence_interval)/2), salaries_df-1)

print('salaries_hr_sample_mean x:', salaries_hr_sample_mean, '\n salaries_hr_sample_std s:', salaries_hr_sample_std, '\n degrees of freedom df:',salaries_df)

# Calculate 95% confidence interval
error_margin = 2*(salaries_hr_sample_std/np.sqrt(salaries_df))
z_error_margin = z*(salaries_hr_sample_std/np.sqrt(salaries_df))
t_error_margin = t*(salaries_hr_sample_std/np.sqrt(salaries_df))


print('\n 95% Confidence interval is :', salaries_hr_sample_mean-error_margin, "-", salaries_hr_sample_mean+error_margin)

# Using z-score python function 

print(f'95% Confidence interval(z-score:{z}) is :', salaries_hr_sample_mean-z_error_margin, "-", salaries_hr_sample_mean+z_error_margin)

# Using t-score python function 
print('\n95% Confidence interval with t stats function is :', st.t.interval(confidence_interval,salaries_df-1, loc=salaries_hr_sample_mean, scale=salaries_hr_sample_std/np.sqrt(salaries_df)))

salaries_hr_sample_mean x: 33.626400000000004
 salaries_hr_sample_std s: 11.794621571725056
 degrees of freedom df: 100

 95% Confidence interval is : 31.267475685654993 - 35.985324314345014
95% Confidence interval(z-score:1.644853626951472) is : 31.6863573929228 - 35.56644260707721

95% Confidence interval with t stats function is : (np.float64(31.28609119407532), np.float64(35.96670880592469))